# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "about"
  weight = 10
  identifier = "about"
  
[[main]]
  name = "Details"
  url = "about#conf"
  weight = 10
  parent = "about"

[[main]]
  name = "Is this workshop for me?"
  url = "about#three-questions"
  weight = 20
  parent = "about"
  
[[main]]
  name = "Overview"
  url = "about#abstract"
  weight = 30
  parent = "about"
  
[[main]]
  name = "Learning objectives"
  url = "about#learning-objectives"
  weight = 40
  parent = "about"
  
[[main]]
  name = "Schedule"
  url = "schedule"
  weight = 30
  
[[main]]
  name = "Materials"
  url = "materials"
  weight = 40
  
[[main]]
  name = "People"
  url = "people"
  weight = 50

[[main]]
  pre = "<i class=\"fab fa-github fa-lg\"></i>"
  name = ""
  url = "https://github.com/rstudio-education/rmd4medicine"
  weight = 60
  
[[main]]
  pre = "<i class=\"fas fa-cloud fa-lg\"></i>"
  name = ""
  url = "https://rstd.io/rmd4medicine-cloud"
  weight = 70
